{% set version = "2.3.1" %}

package:
  name: affine
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/a/affine/affine-{{ version }}.tar.gz
  sha256: d676de66157ad6af99ffd94e0f54e89dfc35b0fb7252ead2ed0ad2dca431bdd0

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  imports:
    - affine
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/sgillies/affine
  license: BSD-3-Clause
  summary: Matrices describing affine transformation of the plane.
  license_family: BSD
  license_file: LICENSE.txt
  description: |
    The Affine package is used to produce the affine transformation
    matrix.
  doc_source_url: https://github.com/sgillies/affine/blob/master/README.rst
  dev_url: https://github.com/sgillies/affine

extra:
  recipe-maintainers:
    - ocefpaf
