{% set version = "2.2.0" %}

package:
  name: affine
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/a/affine/affine-{{ version }}.tar.gz
  sha256: 0e56a6aaf8443366042daa4092a94907c18edf5aba22db9f5e47737b222f4b91

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python

test:
  imports:
    - affine

about:
  home: https://github.com/sgillies/affine
  license: BSD 3-Clause
  summary: 'Matrices describing affine transformation of the plane.'

extra:
  recipe-maintainers:
    - ocefpaf
