{% set name = "affine" %}
{% set version = "3.0b1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/affine-{{ version }}.tar.gz
  sha256: decd53d9035d9540e4f5815b72df672d419867e24aad8ed94ba61948db56d8cc

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - flit-core >=3.2,<4
  run:
    - python >={{ python_min }}
    - attrs

test:
  imports:
    - affine
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Matrices describing affine transformation of the plane
  dev_url: https://github.com/rasterio/affine
  license: BSD-3-Clause
  license_file: LICENSE.txt
  description: |
    The Affine package is used to produce the affine transformation
    matrix.
  doc_source_url: https://github.com/rasterio/affine/blob/main/README.rst

extra:
  recipe-maintainers:
    - mwtoews
    - ocefpaf
