{% set name = "affine" %}
{% set version = "2.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/affine-{{ version }}.tar.gz
  sha256: a24d818d6a836c131976d22f8c27b8d3ca32d0af64c1d8d29deb7bafa4da1eea

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7

test:
  imports:
    - affine
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/sgillies/affine
  license: BSD-3-Clause
  summary: Matrices describing affine transformation of the plane.
  license_family: BSD
  license_file: LICENSE.txt
  description: |
    The Affine package is used to produce the affine transformation
    matrix.
  doc_source_url: https://github.com/sgillies/affine/blob/master/README.rst
  dev_url: https://github.com/sgillies/affine

extra:
  recipe-maintainers:
    - ocefpaf
