{% set version = "2.2.2" %}

package:
  name: affine
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/a/affine/affine-{{ version }}.tar.gz
  sha256: ff0d0f40a90faa651f7bc7fece15bdbb7a0e0658b1e7ba6a03422c21efa7da90

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - affine

about:
  home: https://github.com/sgillies/affine
  license: BSD 3-Clause
  summary: 'Matrices describing affine transformation of the plane.'
  license_family: BSD
  license_file: LICENSE.txt
  description: |
    The Affine package is used to produce the affine transformation
    matrix.
  doc_source_url: https://github.com/sgillies/affine/blob/master/README.rst
  dev_url: https://github.com/sgillies/affine

extra:
  recipe-maintainers:
    - ocefpaf
