travis:
  secure:
    BINSTAR_TOKEN: KekwTczpvpedFS4OYlNcvib/flHCl5ZQ/luvtpiq3wktvT/B8v5SXjb2Gt6Y2Rs2h54wkghzPPTPoMnbmEYCmUPsFsvomu0i/qbNq2+whkBAk8mymEstEaV3rOfOcaoeRPsRrEgAcWv6oJ1ufSmFFMTojgNLqOX9W5rquHWFD6lWAFBxcmCMSRObKP2owlVKwev3Vz2WD+KpsFdGJGfVViMuUM/fwiUN7B3tNjT6KjjprrvB8X7aeo4p93Lk48vH3IZ6aQ5pFzNUi0H5tCm0GHVfPIC2CrQhy6vYKkbJaufVVBzi6lrLxe1yqXTIUFijk63UZE39vcTUAxxm4chIlRkCDFUxGymEOgpx0bxTFUfImeVfFNfK9QzArYflqR6qUjpimZ00WbUVP3vk0OskP16zdjQ5VQEJEgJHgUTp/25qSZaLZhunr5K0GbTWRsQ+MXeIWeo1aj0fkMK1fPVKCkc7VX2ccH1TsHEFxEpcW15mIS56kn4ngYqlBevz/2iMqNI7aygoUMb3uxcMF0ssuo3N3wsd+0ErtAk6f/kku24xtdXUKT0w2otI0Fxw0Mwg0G1fL5wKrK08Z6z+ywdT0u6LV2FIn+bg+1K+q78WER1xNCfGYIrz9SQd7fzEAJEt3kFzkOZtHgfJKTKH/gkJS2ouR2K40QhRG4yjgu60a9A=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
